import {StyleSheet} from 'react-native';
import { appSize } from '../config/AppConstant';

export const styleText = StyleSheet.create({
  heading_2xl_re: {
    fontSize: 72,
    fontWeight: '400',
    lineHeight: 90,
    fontFamily: 'DMSans-Regular',
  },
  heading_2xl_me: {
    fontSize: 72,
    fontWeight: '500',
    lineHeight: 90,
    fontFamily: 'DMSans-Medium',
  },
  heading_2xl_bo: {
    fontSize: 72,
    fontWeight: '700',
    lineHeight: 90,
    fontFamily: 'DMSans-Bold',
  },
  heading_xl_re: {
    fontSize: 60,
    fontWeight: '400',
    lineHeight: 72,
    fontFamily: 'DMSans-Regular',
  },
  heading_xl_me: {
    fontSize: 60,
    fontWeight: '500',
    lineHeight: 72,
    fontFamily: 'DMSans-Medium',
  },
  heading_xl_bo: {
    fontSize: 60,
    fontWeight: '700',
    lineHeight: 72,
    fontFamily: 'DMSans-Bold',
  },
  heading_lg_re: {
    fontSize: 48,
    fontWeight: '400',
    lineHeight: 60,
    fontFamily: 'DMSans-Regular',
  },
  heading_lg_me: {
    fontSize: 48,
    fontWeight: '500',
    lineHeight: 60,
    fontFamily: 'DMSans-Medium',
  },
  heading_lg_bo: {
    fontSize: 48,
    fontWeight: '700',
    lineHeight: 60,
    fontFamily: 'DMSans-Bold',
  },
  heading_md_re: {
    fontSize: 36,
    fontWeight: '400',
    lineHeight: 44,
    fontFamily: 'DMSans-Regular',
  },
  heading_md_me: {
    fontSize: 36,
    fontWeight: '500',
    lineHeight: 44,
    fontFamily: 'DMSans-Medium',
  },
  heading_md_bo: {
    fontSize: 36,
    fontWeight: '700',
    lineHeight: 44,
    fontFamily: 'DMSans-Bold',
  },
  heading_sm_re: {
    fontSize: 30,
    fontWeight: '400',
    lineHeight: 38,
    fontFamily: 'DMSans-Regular',
  },
  heading_sm_me: {
    fontSize: 30,
    fontWeight: '500',
    lineHeight: 38,
    fontFamily: 'DMSans-Medium',
  },
  heading_sm_bo: {
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 38,
    fontFamily: 'DMSans-Bold',
  },
  heading_xs_re: {
    fontSize: 24,
    fontWeight: '400',
    lineHeight: 32,
    fontFamily: 'DMSans-Regular',
  },
  heading_xs_me: {
    fontSize: 24,
    fontWeight: '500',
    lineHeight: 32,
    fontFamily: 'DMSans-Medium',
  },
  heading_xs_bo: {
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 32,
    fontFamily: 'DMSans-Bold',
  },
  body_xl_re: {
    fontSize: 20,
    fontWeight: '400',
    lineHeight: 30,
    fontFamily: 'DMSans-Regular',
  },
  body_xl_me: {
    fontSize: 20,
    fontWeight: '500',
    lineHeight: 30,
    fontFamily: 'DMSans-Medium',
  },
  body_xl_bo: {
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 30,
    fontFamily: 'DMSans-Bold',
  },
  body_lg_re: {
    fontSize: 18,
    fontWeight: '400',
    lineHeight: 28,
    fontFamily: 'DMSans-Regular',
  },
  body_lg_me: {
    fontSize: appSize(16),
    fontWeight: '700',
    color: "#363636",
    lineHeight: appSize(26),
    fontFamily: 'DMSans-Medium',
  },
  body_lg_bo: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 28,
    fontFamily: 'DMSans-Bold',
  },
  body_md_re: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 24,
    fontFamily: 'DMSans-Regular',
  },
  body_md_me: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    fontFamily: 'DMSans-Medium',
  },
  body_md_bo: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 24,
    fontFamily: 'DMSans-Bold',
  },
  body_sm_re: {
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
    fontFamily: 'DMSans-Regular',
  },
  body_sm_me: {
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    fontFamily: 'DMSans-Medium',
    color: '#363636'
  },
  body_sm_bo: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    fontFamily: 'DMSans-Bold',
  },
  body_xs_re: {
    fontSize: 12,
    fontWeight: '400',
    lineHeight: 18,
    fontFamily: 'DMSans-Regular',
  },
  body_xs_me: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 18,
    fontFamily: 'DMSans-Medium',
  },
  body_xs_bo: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    fontFamily: 'DMSans-Bold',
  },
});
