
// 🚀 Generated by cmd 'node generate-assets.js' — DO NOT EDIT MANUALLY!
const Images = {
  background: require('../../assets/images/background.jpeg'),
};

const Icons = {
  wolf: require('../../assets/icons/wolf.jpg'),
};

export default {
  Images,
  Icons,
};
